baseURL = "https://Zhruang.github.io/blog/"
languageCode = 'en-us'
title = 'ZHÈNG Rúyáng’s blog'

theme = "etch"

[params]
  description = "..."
  dark = "auto"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true