baseURL = "https://Zhruang.github.io/blog/"
languageCode = 'en-us'
title = 'some blog!'

theme = "etch"

[params]
  description = "..."
  copyright = "Copyleft 🄯 2022 ZHÈNG Rúyáng"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"