baseURL = "https://Zhruang.github.io/blog/"
languageCode = 'en-us'
title = 'ZHÈNG Rúyáng’s blog'

theme = "etch"

[params]
  description = "..."
  dark = "auto"
  highlight = true

[menu]


[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true